services:

  app:
    build:
      context: ./docker/php-fpm
    image: recrutement
    container_name: recrutement_app
    restart: unless-stopped
    volumes: 
      - ./:/var/www/recrutement
    environment: 
      - APP_ENV=prod
    expose:
      - 9000
    depends_on:
      - db

    networks:
      - backend-network


  server:
    image: nginx:1.26.0-alpine
    container_name: nginx-webserver1
    restart: unless-stopped
    volumes:
      - ./:/var/www/recrutement
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '8085:80'
    depends_on:
      - app
    networks:
      - backend-network


  db:
    image: mysql
    container_name: mysql-server1
    restart: unless-stopped
    ports:
      - '3308:3306'
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: recrutement
    networks:
      - backend-network 


  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin3
    restart: unless-stopped

    ports:
      - 8083:80
    networks:
      - backend-network


   # pour stocker les resultats des requetes frequentes ou les sessions, je l'utilise pour les files d'attentes.
  redis:
    image: redis:alpine
    container_name: redis_1
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - backend-network

volumes:
  db_data:


networks:
  backend-network:
  


